# Generated by Django 5.1.1 on 2024-09-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0002_course_meanstoapply_prerequisite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universitiy',
            new_name='University',
        ),
    ]
