# Generated by Django 5.1.1 on 2024-09-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0003_rename_universitiy_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Data Science', 'Data Science'), ('Artificial Intellegence', 'Artificial Intellegence'), ('Computer Science', 'Computer Science')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_caegory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='admit.coursecategory'),
        ),
    ]
