# Generated by Django 5.1.1 on 2024-09-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0004_coursecategory_course_course_caegory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_caegory',
            new_name='course_category',
        ),
    ]
